# Generated by Django 5.0.6 on 2024-06-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_remove_bookinstance_book_alter_genre_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the movie's natural language (e.g. English, French, Japanese etc.)",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="movieinstance",
            old_name="book",
            new_name="movie",
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(
                help_text='9 Characters <a href="https://developer.imdb.com/documentation/key-concepts/">IMDB ID</a>',
                max_length=13,
                verbose_name="IMDB_ID",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.language",
            ),
        ),
    ]
