# Generated by Django 5.0.6 on 2024-06-04 06:59

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_language_language_name_case_insensitive_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the movie's rating (1.0 to 10.0)",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="language",
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="rating_name_case_insensitive_unique",
                violation_error_message="Rating already exists (case insensitive match)",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.rating",
            ),
        ),
        migrations.DeleteModel(
            name="Language",
        ),
    ]
